name: Discord webhook

on: [push]

jobs:
  webhook:
    runs-on: ubuntu-latest
    steps:

      - name: 'Checkout code'
        uses: actions/checkout@v3

      - name: Send webhook
        env:
          DEV_DISCORD_WEBHOOK: "https://discord.com/api/webhooks/${{ secrets.DEV_WEBHOOK_ID }}/${{ secrets.DEV_WEBHOOK_TOKEN }}"
        run: python .github/workflow_data/discord_push.py
